import type { Metadata } from "next";
import "./globals.css";

import { Montserrat } from "next/font/google";
import Layout from "@/components/layout";
import { Suspense } from "react";
import ClientHydrationWrapper from "@/components/ClientHydrationWrapper";

// Initialize the font with options
const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={` ${montserrat.className}`}>
      <body className={`${montserrat.className}`}>
        <ClientHydrationWrapper>
          <main className="relative h-screen">
            <Layout children={children} />
          </main>
        </ClientHydrationWrapper>
      </body>
    </html>
  );
}
