import type { Metadata } from "next";
import "./globals.css";

import { Montserrat } from "next/font/google";
import Layout from "@/components/layout";
import { Suspense } from "react";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";

import ClientHydrationWrapper from "@/components/ClientHydrationWrapper";
import { ReactQueryProvider } from "@/components/QueryProvider";

// Initialize the font with options
const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  openGraph: {
    images: [
      {
        url: "/images/coverImage.webp",

        alt: "Image description",
        type: "image/png",
      },
    ],
    title: "Funiture home",
    description: "An E-commerce website for furniture",
    url: "https://example.com",
    siteName: "Funiture home",
    locale: "en_US",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Funiture home",
    description: "An E-commerce website for furniture",
    images: ["/images/coverImage.webp"],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={` ${montserrat.className}`}>
      <body className={`${montserrat.className}`}>
        <ClientHydrationWrapper>
          <ReactQueryProvider>
            <main className="relative h-screen">
              <Layout children={children} />
            </main>
            <ReactQueryDevtools initialIsOpen={false} />
          </ReactQueryProvider>
        </ClientHydrationWrapper>
      </body>
    </html>
  );
}
