import type { Metadata } from "next";
import "./globals.css";

import { Montserrat } from "next/font/google";
import Layout from "@/components/layout";

// Initialize the font with options
const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`overflow-y-hidden no-scrollbar bg-[#FFFFFF] ${montserrat.className}`}
    >
      <body className={`${montserrat.className}`}>
        <Layout children={children} />
      </body>
    </html>
  );
}
